#░██████╗████████╗███████╗██╗░░░░░██╗░░░░░░█████╗░██████╗░
#██╔════╝╚══██╔══╝██╔════╝██║░░░░░██║░░░░░██╔══██╗██╔══██╗
#╚█████╗░░░░██║░░░█████╗░░██║░░░░░██║░░░░░███████║██████╔╝
#░╚═══██╗░░░██║░░░██╔══╝░░██║░░░░░██║░░░░░██╔══██║██╔══██╗
#██████╔╝░░░██║░░░███████╗███████╗███████╗██║░░██║██║░░██║
#╚═════╝░░░░╚═╝░░░╚══════╝╚══════╝╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝ v1.4
# Practice Practice by Kira Development
# If you find any bugs or require some sort of support please join our discord
# https://discord.gg/kiradev

License: "your_license_key_here" # Please enter your license to enable Practice.

general:
  enable-join-message: true # Enable messages on join event
  enable-debug: false # Enable debug mode
  clear-empty-bottles: true # Remove bottle from the ground if its empty
  ender-pearl-cooldown: 15 # Ender pearl cooldown per use
  disable-fall-damage: true # Disable fall damage or keep it on
  starting-elo: 1000 # The default Elo before a user gains / loses Elo.
discord:
  enable-webhook: false # Enable discord webhook logs or not
  webhook: "" # Enter your webhook inbetween the speachmarks