#
#    ██████╗░░█████╗░██████╗░██╗░█████╗░███╗░░██╗████████╗
#    ██╔══██╗██╔══██╗██╔══██╗██║██╔══██╗████╗░██║╚══██╔══╝
#    ██████╔╝███████║██║░░██║██║███████║██╔██╗██║░░░██║░░░
#    ██╔══██╗██╔══██║██║░░██║██║██╔══██║██║╚████║░░░██║░░░
#    ██║░░██║██║░░██║██████╔╝██║██║░░██║██║░╚███║░░░██║░░░ v1.4
# Radiant Practice by Kira Development - https://discord.gg/kiradev

general:
  enable-join-message: true
  enable-debug: false
  clear-empty-bottles: true
  ender-pearl-cooldown: 15
  disable-fall-damage: true
  starting-elo: 1000
discord:
  enable-webhook: true
  webhook: "https://discord.com/api/webhooks/1176221079941951662/WOJSLdjpTWtXf8YurhVzDwlzYo_aFSeoonDf0LVNg3ymb_x12QXZ9EPugoHdcHorG7Qg"