general:
  enable-join-message: true
  enable-debug: false
  clear-empty-bottles: true # Remove bottle from the ground if its empty
  ender-pearl-cooldown: 15
  disable-fall-damage: true
  starting-elo: 1000
tablist:
  enable: true
  header: "&bYou're playing on &fPractice &bon &fglacier.net"
  footer: "&7Enjoy your stay!"
discord:
  enable-webhook: false
  webhook: ""